"""L3 boot-fix rule engine — YAML-driven detection and repair over an extracted rootfs.

Each rule in ``rules/*.yaml`` declares detections (when does the failure
pattern apply to this rootfs) and actions (how to repair it):

  detect:       always | path_exists | dir_nonempty | file_glob | file_regex
                | all: [...] (AND group) | any: [...] (OR group)
  actions:      edit (regex replace) | comment_lines | write | guest_shell
  post_action_verify:
                check_files | forbidden_patterns | health_check

Detection conditions return a ``(satisfied, scope)`` pair: ``satisfied`` decides
whether the rule applies, ``scope`` narrows where text actions run. Conditions at
the top level of ``detect`` are OR-ed together, so several independent
fingerprints can live in one rule; ``all:``/``any:`` groups add AND/OR nesting when
one fingerprint needs several facts at once.

Host-side actions mutate the rootfs directory; ``guest_shell`` lines are
collected into ``/firmadyne/iris_rules.sh`` which the emulation container
executes at boot (device nodes and other proc/sysfs work cannot be done
on the host filesystem). Text actions (``edit``/``comment_lines``) skip
files that look binary, so a rule with a broad ``within`` glob can never
corrupt a vendor ELF. Every application returns a report so runs stay
auditable, and dry-run mode reports matches without touching files.

Nothing is applied on faith: ``post_action_verify`` re-reads the rootfs after the
actions ran, so a report states what was verified rather than what was attempted.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path

import yaml

from iris.fsutil import safe_exists as _exists
from iris.fsutil import safe_is_file as _is_file

GUEST_SCRIPT_PATH = "firmadyne/iris_rules.sh"
VERIFY_LOG_PATH = "/etc/scripts/iris_verify.log"
#: Guest-side directory holding the verification log. Spelled as a POSIX literal
#: on purpose: ``Path(VERIFY_LOG_PATH).parent`` renders as ``\etc\scripts`` on a
#: Windows host, and this line is emitted into a script that runs in a Linux
#: chroot — where ``\e`` is an escape, not a path separator.
VERIFY_LOG_DIR = "/etc/scripts"
_SHEBANG = "#!/bin/sh\n# generated by iris L3 rule engine\n"

#: Keys accepted at the top level of a rule document.
_RULE_KEYS = frozenset({"id", "description", "stage", "detect", "actions", "post_action_verify"})
#: Keys accepted inside a single ``detect`` entry. ``within`` narrows a
#: ``file_regex``/``file_glob`` to a sub-tree; ``executable`` is a modifier on
#: ``path_exists``.
_DETECT_KEYS = frozenset({
    "always", "path_exists", "dir_nonempty", "file_glob", "file_regex",
    "all", "any", "within", "executable",
})
#: Keys accepted inside a single ``actions`` entry.
_ACTION_KEYS = frozenset({"write", "edit", "comment_lines", "guest_shell"})


def _read_text(path: Path) -> str:
    # newline="" keeps LF/CRLF endings intact; universal-newline reads would
    # silently rewrite every shell script to CRLF on a Windows host.
    with open(path, encoding="utf-8", errors="ignore", newline="") as fh:
        return fh.read()


def _is_binary(path: Path) -> bool:
    """True for files a text edit would destroy (ELF, squashfs, gz, jffs2clean…).

    ``_read_text`` decodes lossily, so writing one back would silently corrupt a
    vendor binary — which rules now do unattended, in the auto pipeline.
    """
    try:
        with open(path, "rb") as fh:
            return b"\x00" in fh.read(512)
    except OSError:
        return True


def _write_text(path: Path, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)


# An extracted rootfs keeps POSIX symlinks, and on a Windows host a firmware
# ``/sbin -> /bin`` becomes a reparse point that ``stat()`` refuses to resolve
# (``WinError 1920``). ``Path.exists()`` only swallows ENOENT/ENOTDIR/EBADF and
# friends, so that one dead link raised straight through ``apply_rules`` and
# aborted a simulation that was otherwise fine. "Cannot inspect it" and "it is
# not there" are the same answer for rule evaluation; see ``iris.fsutil``, where
# ``_exists``/``_is_file`` below are imported from.


def _ascii_safe(text: str) -> str:
    """Fold a shell line down to ASCII.

    The guest script runs under busybox ``sh`` with a locale nobody controls, and
    every tool that later reads it back (docker cp, grep, a human with cat) decodes
    with *its* locale — a stray ``→`` or emoji makes the whole file unreadable to a
    GBK host. Cosmetic characters get dropped rather than breaking the evidence.
    """
    return "".join(c if ord(c) < 128 else "?" for c in text)


def _can_judge_executable() -> bool:
    """Whether the host filesystem carries a meaningful execute bit.

    ``os.access(X_OK)`` answers True for every regular file on Windows, so using it
    there would make ``path_exists: executable`` match everything. Rather than
    pretend, the modifier is skipped off-POSIX and the rule that asked for it is
    flagged in its warnings.
    """
    return os.name == "posix"


@dataclass
class Rule:
    id: str
    description: str
    stage: str
    detect: list[dict] = field(default_factory=list)
    actions: list[dict] = field(default_factory=list)
    post_action_verify: dict = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)


@dataclass
class RuleReport:
    rule_id: str
    matched: bool
    detail: str = ""
    touched_files: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    verify: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "rule_id": self.rule_id,
            "matched": self.matched,
            "detail": self.detail,
            "touched_files": self.touched_files,
            "warnings": self.warnings,
            "verify": self.verify,
        }


def _unknown_keys(entries: object, known: frozenset[str], where: str, warnings: list[str]) -> None:
    """Record keys the engine has no handler for instead of dropping them quietly.

    A misspelled or aspirational key used to be indistinguishable from a rule that
    simply did not fire, which is how ``file_pattern``/``condition`` and
    ``post_action_verify`` sat in the rule library doing nothing.
    """
    if not isinstance(entries, list):
        return
    for entry in entries:
        if not isinstance(entry, dict):
            warnings.append(f"{where}: expected a mapping, got {type(entry).__name__}")
            continue
        extra = sorted(set(entry) - known)
        if extra:
            warnings.append(f"{where}: unsupported key(s) {', '.join(extra)} ignored")


def _uses_key(entries: object, key: str) -> bool:
    """True if ``key`` appears anywhere in a nested detect structure."""
    if isinstance(entries, dict):
        return key in entries or any(_uses_key(v, key) for v in entries.values())
    if isinstance(entries, list):
        return any(_uses_key(v, key) for v in entries)
    return False


def load_rules(rules_dir: Path) -> list[Rule]:
    """Load every ``*.yaml`` rule in ``rules_dir``, flagging anything unsupported."""
    rules: list[Rule] = []
    for path in sorted(Path(rules_dir).glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not doc:
            continue
        warnings: list[str] = []
        if not isinstance(doc, dict):
            warnings.append(f"{path.name}: rule document is not a mapping")
            doc = {}
        if "id" not in doc:
            warnings.append(f"{path.name}: missing required 'id'")

        _unknown_keys(doc.get("detect"), _DETECT_KEYS, f"{path.name}: detect", warnings)
        _unknown_keys(doc.get("actions"), _ACTION_KEYS, f"{path.name}: actions", warnings)
        extra_top = sorted(set(doc) - _RULE_KEYS)
        if extra_top:
            warnings.append(f"{path.name}: unsupported top-level key(s) {', '.join(extra_top)}")
        if not _can_judge_executable() and _uses_key(doc.get("detect"), "executable"):
            warnings.append(
                f"{path.name}: detect uses 'executable', which this host cannot evaluate "
                "(no POSIX execute bit); the modifier is ignored here"
            )

        rules.append(
            Rule(
                id=doc.get("id", path.stem),
                description=doc.get("description", ""),
                stage=doc.get("stage", "boot"),
                detect=doc.get("detect") or [],
                actions=doc.get("actions") or [],
                post_action_verify=doc.get("post_action_verify") or {},
                warnings=warnings,
            )
        )
    return rules


def _iter_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for p in root.rglob("*"):
        if _is_file(p):
            try:
                if not p.is_symlink():
                    files.append(p)
            except OSError:
                continue
    return files


def _under(f: Path, root: Path, prefix: str) -> bool:
    rel = f.relative_to(root).as_posix()
    return rel == prefix or rel.startswith(prefix + "/")


def _match_glob(rel: str, pattern: str) -> bool:
    return fnmatch(rel, pattern) or fnmatch(Path(rel).name, pattern)


def _scope_union(scopes: list[list[Path]]) -> list[Path]:
    out: list[Path] = []
    seen: set[Path] = set()
    for scope in scopes:
        for f in scope:
            if f not in seen:
                seen.add(f)
                out.append(f)
    return out


def _scope_intersect(scopes: list[list[Path]]) -> list[Path]:
    """Files every sub-condition agreed on, or the widest single scope.

    Two independent fingerprints (``etc/inittab`` here, ``opt/goahead`` there)
    share no file, so the intersection is empty — but the rule still matched and
    text actions still need somewhere to run, so the widest scope wins.
    """
    if not scopes:
        return []
    shared = set(scopes[0])
    for scope in scopes[1:]:
        shared &= set(scope)
    if shared:
        return [f for f in scopes[0] if f in shared]
    return max(scopes, key=len)


def _evaluate(rootfs: Path, cond: dict, files: list[Path]) -> tuple[bool, list[Path]]:
    """Evaluate one detect condition into ``(satisfied, scope)``."""
    if not isinstance(cond, dict) or not cond:
        return False, []

    if "always" in cond:
        return bool(cond["always"]), list(files)

    if "all" in cond or "any" in cond:
        joiner = "all" if "all" in cond else "any"
        subs = cond[joiner]
        subs = subs if isinstance(subs, list) else [subs]
        results = [_evaluate(rootfs, sub, files) for sub in subs]
        if joiner == "all":
            if not results or not all(ok for ok, _ in results):
                return False, []
            return True, _scope_intersect([scope for _, scope in results])
        satisfied = [scope for ok, scope in results if ok]
        if not satisfied:
            return False, []
        return True, _scope_union(satisfied)

    if "path_exists" in cond:
        rel = str(cond["path_exists"]).lstrip("/")
        if not rel or ".." in Path(rel).parts:
            return False, []
        target = rootfs / rel
        try:
            if target.is_symlink() or not target.exists():
                return False, []
            if cond.get("executable") and _can_judge_executable() \
                    and not (target.is_file() and os.access(target, os.X_OK)):
                return False, []
        except OSError:
            return False, []
        if _is_file(target):
            return True, [target]
        return True, [f for f in files if _under(f, rootfs, rel)]

    if "dir_nonempty" in cond:
        rel = str(cond["dir_nonempty"]).lstrip("/")
        if not rel or ".." in Path(rel).parts:
            return False, []
        d = rootfs / rel
        try:
            if not (d.is_dir() and not d.is_symlink() and any(d.iterdir())):
                return False, []
        except OSError:
            return False, []
        return True, [f for f in files if _under(f, rootfs, rel)]

    if "file_glob" in cond:
        pattern = str(cond["file_glob"])
        return True, [f for f in files if _match_glob(f.relative_to(rootfs).as_posix(), pattern)]

    if "file_regex" in cond:
        scope_glob = str(cond.get("within", "*"))
        hits: list[Path] = []
        for f in files:
            if not _match_glob(f.relative_to(rootfs).as_posix(), scope_glob):
                continue
            try:
                text = _read_text(f)
            except OSError:
                continue
            try:
                found = re.search(str(cond["file_regex"]), text)
            except re.error:
                return False, []
            if found:
                hits.append(f)
        return bool(hits), hits

    return False, []


def _apply_action(rootfs: Path, action: dict, files: list[Path], guest_lines: list[str],
                  dry_run: bool, touched: list[str]) -> str:
    if "guest_shell" in action:
        guest_lines.extend(str(line) for line in action["guest_shell"])
        return f"guest_shell x{len(action['guest_shell'])}"

    if "write" in action:
        spec = action["write"]
        rel = str(spec["path"])
        if ".." in Path(rel).parts:
            return f"write refused (path escapes rootfs): {rel}"
        target = rootfs / rel.lstrip("/")
        touched.append(rel)
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            _write_text(target, spec.get("content", ""))
        return f"write {rel}"

    if "edit" in action:
        spec = action["edit"]
        pattern = re.compile(spec["regex"])
        changed: list[str] = []
        rels: list[str] = []
        for f in files:
            rel = f.relative_to(rootfs).as_posix()
            if not _match_glob(rel, spec.get("within", "*")):
                continue
            if _is_binary(f):
                continue
            try:
                text = _read_text(f)
            except OSError:
                continue
            new_text, n = pattern.subn(spec["replacement"], text)
            if n and not dry_run:
                _write_text(f, new_text)
            if n:
                changed.append(f"{rel} x{n}")
                rels.append(rel)
        touched.extend(rels)
        return "edit: " + (", ".join(changed) if changed else "no change")

    if "comment_lines" in action:
        spec = action["comment_lines"]
        pattern = re.compile(spec["regex"])
        prefix = spec.get("prefix", "#IRIS: ")
        changed = []
        rels = []
        for f in files:
            rel = f.relative_to(rootfs).as_posix()
            if not _match_glob(rel, spec.get("within", "*")):
                continue
            if _is_binary(f):
                continue
            try:
                lines = _read_text(f).splitlines(keepends=True)
            except OSError:
                continue
            out, n = [], 0
            for line in lines:
                stripped = line.lstrip()
                if n < spec.get("max", 10**6) and pattern.search(stripped) and not stripped.startswith("#"):
                    indent = line[: len(line) - len(stripped)]
                    out.append(f"{indent}{prefix}{stripped}")
                    n += 1
                else:
                    out.append(line)
            if n:
                if not dry_run:
                    _write_text(f, "".join(out))
                changed.append(f"{rel} x{n}")
                rels.append(rel)
        touched.extend(rels)
        return "comment_lines: " + (", ".join(changed) if changed else "no change")

    return f"unknown action {list(action)}"


def _verify_lines(rule: Rule, spec: dict) -> list[str]:
    """Render ``health_check`` into guest-shell lines that log their own verdict.

    The check runs inside the container (it inspects live processes), so it cannot
    be answered on the host. Emitting it into the same script that performs the
    repairs keeps the evidence next to the action it judges — and every verdict,
    pass or fail, lands in one file for post-mortem.
    """
    check = spec.get("health_check")
    if not isinstance(check, dict) or not check.get("command"):
        return []
    command = str(check["command"])
    expected = str(check.get("expected_exit_code", 0))
    log_line = f"rule={rule.id} expected={expected} rc=$_iris_rc"
    return [
        f"# IRIS post-action verify: {rule.id}",
        f"mkdir -p {VERIFY_LOG_DIR} 2>/dev/null || true",
        f"{command} >/dev/null 2>&1; _iris_rc=$?",
        f"if [ \"$_iris_rc\" = \"{expected}\" ]; then",
        f"  echo \"IRIS-VERIFY OK   rule={rule.id} rc=$_iris_rc\" >> {VERIFY_LOG_PATH}",
        "else",
        f"  echo \"IRIS-VERIFY FAIL {log_line}\" >> {VERIFY_LOG_PATH}",
        "fi",
    ]


def _run_verify(rootfs: Path, rule: Rule, dry_run: bool) -> list[str]:
    """Re-read the rootfs and report what the actions actually achieved."""
    spec = rule.post_action_verify
    if not spec:
        return []
    results: list[str] = []
    if dry_run:
        return ["skipped (dry-run)"]

    for item in spec.get("check_files") or []:
        if not isinstance(item, dict) or not item.get("path"):
            continue
        rel = str(item["path"]).lstrip("/")
        if ".." in Path(rel).parts:
            results.append(f"check_files refused unsafe path: {rel}")
            continue
        present = _exists(rootfs / rel)
        if item.get("must_exist") and not present:
            results.append(f"MISSING expected file: {rel}")
        elif item.get("must_not_exist") and present:
            results.append(f"STILL PRESENT forbidden file: {rel}")
        else:
            note = item.get("expected", "")
            results.append(f"{'present' if present else 'absent '}: {rel}{f' ({note})' if note else ''}")

    for item in spec.get("forbidden_patterns") or []:
        if not isinstance(item, dict) or not item.get("pattern"):
            continue
        rel = str(item.get("in_file", "")).lstrip("/")
        if not rel or ".." in Path(rel).parts:
            results.append(f"forbidden_pattern refused unsafe path: {rel}")
            continue
        target = rootfs / rel
        if not _is_file(target) or _is_binary(target):
            results.append(f"forbidden_pattern {item['pattern']}: {rel} not present — clear")
            continue
        try:
            hits = re.findall(str(item["pattern"]), _read_text(target))
        except (re.error, OSError) as exc:
            results.append(f"forbidden_pattern {item['pattern']} in {rel}: check failed ({exc})")
            continue
        if hits:
            results.append(f"FORBIDDEN pattern {item['pattern']} still in {rel} ({len(hits)} hit(s))")
        else:
            results.append(f"forbidden_pattern {item['pattern']}: clear in {rel}")

    deferred = _verify_lines(rule, spec)
    if deferred:
        results.append(f"health_check deferred to guest ({len(deferred)} lines -> {VERIFY_LOG_PATH})")

    return results


def apply_rules(
    rootfs_dir: Path,
    rules: list[Rule],
    dry_run: bool = True,
) -> list[RuleReport]:
    """Evaluate rules against an extracted rootfs; apply repairs unless dry-run."""
    rootfs = Path(rootfs_dir)
    files = _iter_files(rootfs)
    reports: list[RuleReport] = []
    all_guest_lines: list[str] = []

    for rule in rules:
        conditions = rule.detect or [{"always": True}]
        matched_files: list[Path] = []
        seen: set[Path] = set()
        satisfied = False
        for cond in conditions:
            ok, scope = _evaluate(rootfs, cond, files)
            if not ok:
                continue
            satisfied = True
            for f in scope:
                if f not in seen:
                    seen.add(f)
                    matched_files.append(f)

        if not satisfied:
            reports.append(RuleReport(rule.id, matched=False, warnings=rule.warnings))
            continue

        guest_lines: list[str] = []
        touched: list[str] = []
        summaries = [_apply_action(rootfs, action, matched_files, guest_lines, dry_run, touched)
                     for action in rule.actions]
        all_guest_lines.extend(guest_lines)
        all_guest_lines.extend(_verify_lines(rule, rule.post_action_verify))
        detail = "; ".join(summaries) or "fingerprint match (no actions)"
        reports.append(RuleReport(
            rule.id,
            matched=True,
            detail=detail,
            touched_files=touched,
            warnings=rule.warnings,
            verify=_run_verify(rootfs, rule, dry_run),
        ))

    if all_guest_lines and not dry_run:
        script = _SHEBANG + "\n".join(_ascii_safe(line) for line in all_guest_lines) + "\n"
        target = rootfs / GUEST_SCRIPT_PATH
        target.parent.mkdir(parents=True, exist_ok=True)
        _write_text(target, script)

    return reports


def report_json(reports: list[RuleReport]) -> str:
    return json.dumps([r.to_dict() for r in reports], indent=2, ensure_ascii=False)
