"""L3 boot-fix rule engine — YAML-driven detection and repair over an extracted rootfs.

Each rule in ``rules/*.yaml`` declares detections (when does the failure
pattern apply to this rootfs) and actions (how to repair it):

  detections:  always | file_glob | file_regex | dir_nonempty
  actions:     edit (regex replace) | comment_lines | write | guest_shell

Host-side actions mutate the rootfs directory; ``guest_shell`` lines are
collected into ``/firmadyne/iris_rules.sh`` which the emulation container
executes at boot (device nodes and other proc/sysfs work cannot be done
on the host filesystem). Every application returns a report so runs stay
auditable, and dry-run mode reports matches without touching files.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path

import yaml

GUEST_SCRIPT_PATH = "firmadyne/iris_rules.sh"
_SHEBANG = "#!/bin/sh\n# generated by iris L3 rule engine\n"


@dataclass
class Rule:
    id: str
    description: str
    stage: str
    detect: list[dict] = field(default_factory=list)
    actions: list[dict] = field(default_factory=list)


@dataclass
class RuleReport:
    rule_id: str
    matched: bool
    detail: str = ""
    touched_files: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "rule_id": self.rule_id,
            "matched": self.matched,
            "detail": self.detail,
            "touched_files": self.touched_files,
        }


def load_rules(rules_dir: Path) -> list[Rule]:
    rules: list[Rule] = []
    for path in sorted(rules_dir.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not doc:
            continue
        rules.append(
            Rule(
                id=doc["id"],
                description=doc.get("description", ""),
                stage=doc.get("stage", "boot"),
                detect=doc.get("detect", []),
                actions=doc.get("actions", []),
            )
        )
    return rules


def _iter_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for p in root.rglob("*"):
        try:
            if p.is_file() and not p.is_symlink():
                files.append(p)
        except OSError:
            continue
    return files


def _match_glob(rel: str, pattern: str) -> bool:
    return fnmatch(rel, pattern) or fnmatch(Path(rel).name, pattern)


def _detect(rootfs: Path, cond: dict, files: list[Path]) -> list[Path]:
    if "always" in cond:
        return files
    hits: list[Path] = []
    for f in files:
        rel = f.relative_to(rootfs).as_posix()
        if "file_glob" in cond:
            if _match_glob(rel, cond["file_glob"]):
                hits.append(f)
        elif "dir_nonempty" in cond:
            d = rootfs / cond["dir_nonempty"].lstrip("/")
            if d.is_dir() and any(d.iterdir()):
                hits.append(d)
        elif "file_regex" in cond:
            g = cond.get("within", "*")
            if not _match_glob(rel, g):
                continue
            try:
                text = f.read_text(errors="ignore")
            except OSError:
                continue
            if re.search(cond["file_regex"], text):
                hits.append(f)
    return hits


def _apply_action(rootfs: Path, action: dict, files: list[Path], guest_lines: list[str],
                  dry_run: bool, touched: list[str]) -> str:
    if "guest_shell" in action:
        guest_lines.extend(str(line) for line in action["guest_shell"])
        return f"guest_shell x{len(action['guest_shell'])}"

    if "write" in action:
        spec = action["write"]
        target = rootfs / str(spec["path"]).lstrip("/")
        touched.append(str(spec["path"]))
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(spec.get("content", ""), encoding="utf-8")
        return f"write {spec['path']}"

    if "edit" in action:
        spec = action["edit"]
        pattern = re.compile(spec["regex"])
        changed: list[str] = []
        rels: list[str] = []
        for f in files:
            rel = f.relative_to(rootfs).as_posix()
            if not _match_glob(rel, spec.get("within", "*")):
                continue
            try:
                text = f.read_text(errors="ignore")
            except OSError:
                continue
            new_text, n = pattern.subn(spec["replacement"], text)
            if n and not dry_run:
                f.write_text(new_text, encoding="utf-8")
            if n:
                changed.append(f"{rel} x{n}")
                rels.append(rel)
        touched.extend(rels)
        return "edit: " + (", ".join(changed) if changed else "no change")

    if "comment_lines" in action:
        spec = action["comment_lines"]
        pattern = re.compile(spec["regex"])
        prefix = spec.get("prefix", "#IRIS: ")
        changed = []
        rels = []
        for f in files:
            rel = f.relative_to(rootfs).as_posix()
            if not _match_glob(rel, spec.get("within", "*")):
                continue
            try:
                lines = f.read_text(errors="ignore").splitlines(keepends=True)
            except OSError:
                continue
            out, n = [], 0
            for line in lines:
                stripped = line.lstrip()
                if n < spec.get("max", 10**6) and pattern.search(stripped) and not stripped.startswith("#"):
                    indent = line[: len(line) - len(stripped)]
                    out.append(f"{indent}{prefix}{stripped}")
                    n += 1
                else:
                    out.append(line)
            if n:
                if not dry_run:
                    f.write_text("".join(out), encoding="utf-8")
                changed.append(f"{rel} x{n}")
                rels.append(rel)
        touched.extend(rels)
        return "comment_lines: " + (", ".join(changed) if changed else "no change")

    return f"unknown action {list(action)}"


def apply_rules(
    rootfs_dir: Path,
    rules: list[Rule],
    dry_run: bool = True,
) -> list[RuleReport]:
    """Evaluate rules against an extracted rootfs; apply repairs unless dry-run."""
    rootfs = Path(rootfs_dir)
    files = _iter_files(rootfs)
    reports: list[RuleReport] = []
    all_guest_lines: list[str] = []

    for rule in rules:
        conditions = rule.detect or [{"always": True}]
        matched_files: list[Path] = []
        for cond in conditions:
            for f in _detect(rootfs, cond, files):
                if f not in matched_files:
                    matched_files.append(f)

        if not matched_files:
            reports.append(RuleReport(rule.id, matched=False))
            continue

        guest_lines: list[str] = []
        touched: list[str] = []
        summaries = []
        scope_files = [f for f in matched_files if f.is_file()] or files
        for action in rule.actions:
            summaries.append(_apply_action(rootfs, action, scope_files, guest_lines, dry_run, touched))
        all_guest_lines.extend(guest_lines)
        detail = "; ".join(summaries) or "fingerprint match (no actions)"
        reports.append(RuleReport(rule.id, matched=True, detail=detail, touched_files=touched))

    if all_guest_lines and not dry_run:
        script = _SHEBANG + "\n".join(all_guest_lines) + "\n"
        target = rootfs / GUEST_SCRIPT_PATH
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(script, encoding="utf-8")

    return reports


def report_json(reports: list[RuleReport]) -> str:
    return json.dumps([r.to_dict() for r in reports], indent=2, ensure_ascii=False)
